[package]
name = "ellp"
version = "0.1.0"
authors = ["Kurt Ehlert <kwehlert@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Linear programming library that provides primal and dual simplex solvers."
repository = "https://github.com/kehlert/ellp"
keywords = ["linear programming", "optimization", "linear optimization", "primal", "dual", "simplex", "solver"]
categories = ["mathematics", "science"]
[dependencies]
log = "*"
nalgebra = "*"
thiserror = "*"

[dev-dependencies]
chrono = "*"
fern = {version = "*", features = ["colored"]}
paste = "*"