[package]
name = "ellp"
version = "0.1.0"
authors = ["Kurt Ehlert <kwehlert@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "*"
sprs = "*"
ndarray = "*"